<?php $this->headTitle('Blessed Alliance Team'); ?>
<section id='member-location'>
    <div class="container">
        <h1>Our Members Around the World</h1>
        <div id="team-members" style="height: 500px"></div>
    </div>
</section>
<div class="divider"><br></div>


<?php
    $this->headLink()->prependStylesheet($this->basePath('/assets/blessed-alliance/css/maps/jquery-jvectormap-2.0.3.css'));
    
    $this->inlineScript()->prependFile($this->basePath('/assets/blessed-alliance/js/maps/members.js'))
        ->prependFile($this->basePath('/assets/blessed-alliance/js/maps/jquery-jvectormap-world-mill-en.js'))
        ->prependFile($this->basePath('/assets/blessed-alliance/js/maps/members-data.js'))
        ->prependFile($this->basePath('/assets/blessed-alliance/js/maps/jquery-jvectormap-2.0.3.min.js'));
?>